[pytest]
pythonpath = .
# This suppresses the annoying DeprecationWarnings we saw
# Suppress general deprecation warnings
filterwarnings =
    ignore::DeprecationWarning

# Default flags
addopts = -v --cov=app --cov=pipelines --cov-report=term-missing